/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'giri' at '17/02/17 22:57' with Gradle 3.0
 *
 * @author giri, @date 17/02/17 22:57
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
